is_booked updated
asardie/Calendar pull request #26
Opened 2020-11-13 08:53 UTC by kmothibeJHB

2020-11-13 08:57 UTC, asardie approved these changes

2020-11-13 09:04 UTC, asardie commented on is_booked.py
> +    service = build('calendar', 'v3', credentials=creds)
use auth.create_service()

2020-11-13 09:05 UTC, asardie requested changes
auth.create_service

2020-11-25 09:36 UTC, nhlanhlathemba approved these changes

2020-11-25 10:28 UTC, asardie approved these changes

2020-11-30 08:16 UTC, closed without merging